name: organization checks

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Scony/godot-gdscript-toolkit@master
    - run: gdformat --check scripts/
    - run: gdlint scripts/
  
  structure-checks:
    name: 'Structure checks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x .github/scripts/structure_check.sh
          bash .github/scripts/structure_check.sh